version: '3'

services:
  frontend:
    image: scoringapp.azurecr.io/dashboard
    container_name: scoringapp.azurecr.io/dashboard  
    build: dashboard
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./storage:/storage
  backend:
    image: scoringapp.azurecr.io/api
    container_name: scoringapp.azurecr.io/api
    build:
      context: ./
      dockerfile: api/Dockerfile  
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage