# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - scoring-webapp

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://scoringapp.azurecr.io/
          username: ${{ secrets.AZURE_CONTAINER_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_PASSWORD }}
      
      # - name: Build docker-compose image
      #   run: docker compose build
      
      # - name: Push docker-compose image to registry
      #   run: docker compose push

      - name: Build and push dashboard to registry
        uses: docker/build-push-action@v2
        with:
          context: ./dashboard
          push: true
          tags: scoringapp.azurecr.io/dashboard:${{ github.sha }}
          file: ./dashboard/Dockerfile

      - name: Build and push api to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: scoringapp.azurecr.io/api:${{ github.sha }}
          file: ./api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy Dashboard to Azure Web App
        id: deploy-to-webapp-dashboard
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'scoringapp-dashboard'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DASHBOARD }}
          # images: 'scoringapp.azurecr.io/dashboard'
          # images: 'scoringapp.azurecr.io/${{ secrets.AZURE_CONTAINER_USERNAME }}/latest:${{ github.sha }}'
          images: 'scoringapp.azurecr.io/dashboard:${{ github.sha }}'

      - name: Deploy API to Azure Web App
        id: deploy-to-webapp-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'scoringapp-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          # images: 'scoringapp.azurecr.io/dashboard'
          images: 'scoringapp.azurecr.io/api:${{ github.sha }}'